version: "3.2"

services:
  app:
    build:
      dockerfile: "./docker/Dockerfile"
      context: .
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    command: bash -c "python bot.py"
